### ISSUE TITLE
Standardize the margin of Leaflet map controls

### ISSUE THREAD

**Issue by joaopalmeiro** [FogosPT/fogospt#109]
Hi! 👋 

**Is your feature request related to a problem? Please describe.**

No. This request is just a suggestion for styling improvements. 

Right now, the Leaflet map controls (the boxes at the top of the map) have a non-uniform margin, being larger at the bottom:

<img width="1582" alt="Screenshot 2024-08-21 at 14 43 00" src="https://github.com/user-attachments/assets/cd44627e-2a38-456e-993b-279d115655af">

This behavior is due to the margin below each control item (`margin-bottom: .5rem;`), including the last one. This margin is applied by [Bootstrap](https://github.com/twbs/bootstrap/blob/v4.3.1/scss/_reboot.scss#L290-L294).

**Describe the solution you'd like**

Uniform margins for Leaflet map controls.

A possible implementation, if I'm correct, would be to include some custom CSS at the end of the [app.scss](https://github.com/FogosPT/fogospt/blob/b7442ece192d4b005fe3b66e5e2d40c1d2ff9259/fogospt/resources/assets/sass/app.scss) file (or in another file that you consider more appropriate) and leverage one CSS selector ([`:last-child`](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child)) to achieve this result:

<img width="1582" alt="Screenshot 2024-08-21 at 14 40 13" src="https://github.com/user-attachments/assets/87ed0e40-97e3-4632-9cf9-7388bc05fe9c">

```css
.leaflet-control label:last-child {
    margin-bottom: unset;
}
```

Regarding the custom CSS, there are other options, such as overriding the `margin-bottom` value for all cases with the intended values (so the control spacing/margin is defined explicitly in the application), apply `margin-top` in a similar way, or explicitly setting it to `0` instead of `unset` it. However, the above option seems to me to be the simplest one.

Let me know what you think and if I can open a PR. Thanks!

**Additional context**

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 127.0.6533.89

**Comment by joaopalmeiro** [comment]
Claro! Vou tentar meter o projeto a correr localmente e vou dando novidades.

**Comment by tomahock** [comment]
Já nao o levanto há algm tempo, mas tenho ideia que o docker tá operacional! qq coisa apita que tento ajuda!

Obrigado

**Comment by joaopalmeiro** [comment]
Consegui! Vou tratar do PR.

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/e90eead8-e9e3-4a39-a0f2-906883cc7485">

**Comment by joaopalmeiro** [comment]
Pronto para revisão, @tomahock: https://github.com/FogosPT/fogospt/pull/110
