### ISSUE TITLE
Estado de incêndio por vezes não corresponde ao item selecionado 

### ISSUE THREAD

**Issue by lmarcelocc** [FogosPT/fogospt#115]
**Describe the bug**
Estado de incêndio por vezes não corresponde ao item selecionado (ver screenshot e info abaixo)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to fogos.pt
2. Click on a fire (I've selected https://fogos.pt/fogo/20241157148)
3. Scroll down to "Estado"

**Expected behaviour**
Should show stats related to selected item

**Screenshots**
![image](https://github.com/user-attachments/assets/ca9fb218-9afe-4b98-958f-90dceaebdd70)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome Version 128.0.6613.120 (Official Build) (arm64)

**Comment by tomahock** [comment]
Obrigado! Estamos a tratar

**Comment by tomahock** [comment]
Corrigido!
