### ISSUE TITLE
Areal recourses calculation.

### ISSUE THREAD

**Issue by spacecabbie** [FogosPT/fogospt#116]
Hi I was just wondering how Areal resources are calculated, I'm tracking most of the planes in helicopters via flightradar24. 

For example today 19/09/2024 13:55
It's saying at least seven aerial resources around Viseu.
But I can only track AT8T in the air nowhere near. And the helicopter on its way to Lisboa. 

Does it include drones etc?

**Comment by tomahock** [comment]
The total count is given by ANEPC.

Not all airplanes and helicopters have adsb transmitter. You can only see on FR24 the ones that have. For example, the AT8T  that you see arround Viseu have another one always with it. the portuguese planes always are in pairs.

The drones are also included in the count. In the past we had the count by the type (plane, heli, other) currently we only have the total number.

**Comment by spacecabbie** [comment]
Ah thank you both for explaining this, I assumed it was not allowed anymore to fly without a A-DSB.... Assumptions will be the death of me one day should always check.
