### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogospt#13]
Support for multi language
Add at least EN

**Comment by Rubemlrm** [comment]
Relative to this, you want to use database for this or only lang files ?

**Comment by aariops** [comment]
I can help with this. 
Any ideas about the file format you will use for strings of text?

**Comment by tomahock** [comment]
Yes! We will use Laravel Localization tools:
https://laravel.com/docs/5.6/localization

**Comment by Rubemlrm** [comment]
We are already implementing that :) today i will do a pull request and you can help :)
