### ISSUE TITLE
Minor css error in counters

### ISSUE THREAD

**Issue by rgllm** [FogosPT/fogospt#39]
![screenshot 2018-08-11 at 11 24 52](https://user-images.githubusercontent.com/9056941/43990863-80fbdd24-9d59-11e8-9e97-bff95b7536c0.jpg)

**Comment by Rubemlrm** [comment]
hi there @rgllm you find this bug in which situation? I've just found a bug like that on stats page. It was on the same place ? or in another context?

**Comment by rgllm** [comment]
Mine was on the homepage, when a point in the map (fire) was clicked. Not related with stats page.
