### ISSUE TITLE
Notifications - if edge => not supported

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogospt#51]
https://github.com/firebase/firebase-js-sdk/issues/757

**Comment by telmo-rodrigues** [comment]
Take a look and check if you agree with disabling IE and Edge for now. At least until there's any API support for it.

https://github.com/telmo-rodrigues/fogospt/commit/81818fa9ba5e50a56ccb779c907470ff59c98db0

**Comment by tomahock** [comment]
@telmo-rodrigues that will work! PR to merge!
