### ISSUE TITLE
Timestamps off by 12 hours?

### ISSUE THREAD

**Issue by jonnyparris** [FogosPT/fogospt#75]
<img width="452" alt="Fogos_pt_-_Fire_in_Setúbal__Almada__Almada__Cova_Da_Piedade__Pragal_And_Cacilhas_-" src="https://user-images.githubusercontent.com/6400000/65512821-e7343400-ded1-11e9-9f86-c09a9d7235c1.png">

Not sure which of these times are authoritative but they should probably agree with each other at least?

**Comment by jonnyparris** [comment]
![](https://media2.giphy.com/media/efNxYoJxgusMQOgVql/giphy.gif)

**Comment by guivazcabral** [comment]
Sorry. I

**Comment by guivazcabral** [comment]
Sorry. I checked on my end and, as I'm seeing the timestamps in 24 hour format, I didn't notice the error at first. You're absolutely right about the inconsistencies. The date at the top should be AM and not PM.

**Comment by tomahock** [comment]
I think everything is fine! reopen if not!
