### ISSUE TITLE
Can't use docker-compose files in windows with WSL and Without

### ISSUE THREAD

**Issue by Rubemlrm** [FogosPT/fogospt#80]
Hi,

I'm trying to start the fogos.pt project using the provided docker-compose files and i'm getting the following errors:

With this command: 
`docker-compose -f docker-compose.dev.yml up`

I got this error when i've executed this outside of WSL:

`WARNING: The PWD variable is not set. Defaulting to a blank string.
ERROR: The Compose file is invalid because:
Service php has neither an image nor a build context specified. At least one must be provided.`

When i run the same command inside the WSL i got this:
`ERROR: The Compose file is invalid because:
Service php has neither an image nor a build context specified. At least one must be provided.
`

The php  service error happens with the default docker-compose file too. Relative to the PWD variable i can understand the cause, i'm more curious about the service php error. 

At this moment i'm trying to run this using Windows 10 with release 2004 and WSL 2 enabled.

**Comment by FernandoMiguel** [comment]
I have no experience with docker on windows (wsl1 or wsl2)

**Comment by FernandoMiguel** [comment]
years ago I remember reading windows doesnt really fill in env vars like $PWD, but again, not something i personally use, so cant say.

PRs welcome

**Comment by FernandoMiguel** [comment]
seems to be an issue with windows CMD.
if you use gitbash, powershell or Windows Terminal, works as expected
https://blog.codewithdan.com/docker-volumes-and-print-working-directory-pwd/
https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10
