### ISSUE TITLE
The start of a fire entry does not have a date

### ISSUE THREAD

**Issue by mamoit** [FogosPT/fogospt#83]
This makes it a little bit weird to read on a multi day situation, since on a quick glance it seems that the start actually happened more recently than all the other entries on the timeline.

Screenshot on mobile taken from [this specific fire](https://fogos.pt/fogo/2020050017687), but it also happens on desktop.
![Screenshot_20200727-192808_Brave](https://user-images.githubusercontent.com/4675358/88580305-5410e100-d043-11ea-94d1-2c57dcaef63a.png)

PS: [in**í**cio](https://dicionario.priberam.org/in%C3%ADcio)... [in**i**cio](https://dicionario.priberam.org/inicio)...
I seriously don't know and Priberam is not helping, but I guess that string comes from upstream.

**Comment by tomahock** [comment]
<img width="523" alt="Screenshot 2020-07-27 at 20 12 58" src="https://user-images.githubusercontent.com/794581/88581778-963b2200-d045-11ea-8761-dcc7e0cb7a6f.png">

Fixed!
Thank you for your feedback!
